### PR TITLE
Speed things up

### LINKED ISSUE #162: Redundant checks?
I don't think we need these anymore. Given that a cloudflare response with 503 status always contains a challenge, if both of these checks fail, it's possible that the challenge page would be erroneously returned without any error being thrown. If these checks are to be retained then an error should be thrown if they are false.
https://github.com/codemanki/cloudscraper/blob/1a6ad2a6f324a534046ca215bfb1b4a1fe817f0e/index.js#L168-L171

Edit: Oops, I mean this to be about `isChallengePresent` and not `isRedirectChallengePresent` since it's clearly still useful.

### PR DESCRIPTION
**Pull request by pro-src**
Fixes #162 and removes a test which is no longer needed
Reduces the timeout to 5 seconds (Cloudflare requires 4 seconds)
Increases the accuracy of challenge timing.
Error asap instead of after challenge delay.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -331,20 +326,11 @@ function processResponseBody (options, response, body) {
     body = body.toString(options.realEncoding);
     // The resolveWithFullResponse option will resolve with the response
     // object. This changes the response.body so it is as expected.
-    response.body = body;
-
-    if (response.isCloudflare) {
```
Comment (codemanki) [inline index.js]: Why was this removed?

Comment (pro-src) [reply index.js]: TBH, it never made any sense to me but with recent changes it became clear that it wasn't necessary.
