### PR TITLE
Remove a few problematic TLSv1.0 ciphers

### LINKED ISSUE #211: CaptchaError: captcha v4.0.1 (SSL negotiation)
```
var uri = "https://nanime.in";
  var cloudscraper = require("cloudscraper").defaults({
    headers: {
      Connection: "keep-alive",
      "User-Agent":
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
      Accept:       "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Accept-Language": "en-US,en;q=0.9"
    }
  });

  cloudscraper.get(uri, function(error, response, body) {
    if (error) {
      throw error;
      res.send(error);
      next();
    } else {
      console.log(body);

      res.send(body);
      next();
    }
  });
```
```

/media/karnadi/Boice/Proyek/scraper-api/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^
CaptchaError: captcha

```

### PR DESCRIPTION
**Pull request by pro-src**
This PR fixes the same problem as #212 but without adding TLSv1.3 options for older openssl versions. As noted in this https://github.com/codemanki/cloudscraper/issues/211#issuecomment-492320464 , the TLSv1.3 options aren't the actual reason why #212 resolved the problem for the OP.

This is a minimal solution and is known to avoid the CAPTCHA on the latest version of openssl as well as older versions. It is reproducible on Node.js v10.8.0 which uses openssl v1.1.0h

Fixes #211

### CODE REVIEW

**Comment by codemanki** [comment]
I will take a look today. Sorry, I'm traveling now and have a very limited
internet access :)

**Comment by pro-src** [comment]
Thanks :)

File: index.js [hunk 1]
```diff
@@ -37,8 +37,10 @@ function defaults (params) {
     decodeEmails: false,
     // Support gzip encoded responses
     gzip: true,
-    // Adds secure TLSv1.3 ciphers when using older openssl versions
-    agentOptions
+    agentOptions: {
```
Comment (codemanki) [inline index.js]: Could you please also update the docs?

Comment (pro-src) [reply index.js]: I would but do we want to document this? It's a rather advanced option that average users don't need to be aware of or play with when using the library as intended. The brave can always read the source. If you think it needs to be mentioned in the README, I'll document it.

Comment (pro-src) [reply index.js]: Then again, maybe I'm making too many assumptions about the user base. Just let me know and I'll make the changes. :)

**Comment by codemanki** [comment]
I would appreciate if you could do that :) otherwise I can take care of it.
I would prefer these settings to be documented well, as they are already
present in the README, so why not to keep them up to date?

File: index.js (hunk 1 above)
Comment (codemanki) [reply index.js]: I would appreciate if you could do that :) otherwise I can take care of it.
I would prefer these settings to be documented well, as they are already
present in the README, so why not to keep them up to date?

Comment (pro-src) [reply index.js]: Updated.

**Comment by codemanki** [comment]
Awesome! Thank you :) Merging and releasing
