### PR TITLE
Skip non-challenge response body types

### LINKED ISSUE #108: Tests fail in strict mode
A few tests are currently failing in strict mode. This is due to `test/helper` freezing the fake request result and cloudscraper trying to update `response.body` in the `processResponseBody` function. We could fix this so tests don't rely on the fake request result being immutable and `test/helper` doesn't freeze anything at all. Although, it makes for less readable tests. If tests are rewritten as per #104, there won't be a fake request result to worry about.

### LINKED ISSUE #109: Add global module "use strict" statement
Related to #108

### LINKED ISSUE #132: [Bug] [V3] Option json
Setting `json` option property to true, seems to return the string `[object Object]` as `body`.

From `node-request` README:
```
json - sets body to JSON representation of value and adds Content-type: application/json header. Additionally, parses the response body as JSON.
```

### LINKED ISSUE #134: [Bug] [V3] Option body
Using passing Object as body option will result into this error:
```
Argument error, options.body.
_http_outgoing.js:607
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
    at write_ (_http_outgoing.js:607:11)
    at ClientRequest.write (_http_outgoing.js:579:10)
    at Request.write (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:1500:27)
    at end (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:549:18)
    at Immediate.<anonymous> (C:\Users\Roy\AppData\Roaming\npm\node_modules\cloudscraper\node_modules\request\request.js:578:7)
    at processImmediate (timers.js:637:19)
```

### PR DESCRIPTION
**Pull request by pro-src**
I've updated/added tests and added a global use strict statement.

Fixes #132 
Fixes #108 
Fixes #109 

Closes #134

### CODE REVIEW

**Comment by pro-src** [comment]
@codemanki, you can see that the coverage decrease applies only to that one test: https://coveralls.io/builds/22094232/source?filename=index.js#L317

It's the test that I added recently to verify error checking in response's real encoding. I'm not sure how to write that test given the changes that I just made. It's hard to test period unless you have a fixture that doesn't cause a CaptchaError/CloudflareError in the validate function when converted to utf8 encoding but does in it's original encoding. I couldn't think of anything like that so I just used property getters to simulate a test. We can also fix that test later.

**Comment by pro-src** [comment]
@codemanki, I'll replace that poor comment a little later if you haven't merged this by then. You can adjust it for me if you want :D

**Comment by pro-src** [comment]
@codemanki, it LGTM

File: index.js [hunk 1]
```diff
@@ -129,6 +131,11 @@ function processRequestResponse (options, error, response, body) {
     /^cloudflare/i.test('' + response.caseless.get('server')) &&
     /text\/html/i.test('' + response.caseless.get('content-type'));
 
+  // If body isn't a buffer, this is a custom response body.
+  if (!Buffer.isBuffer(body)) {
```
Comment (codemanki) [inline index.js]: Should we maybe move this to the `processResponseBody` ? So the code responsible for handling the response is in one place?

Comment (codemanki) [reply index.js]: 🤔 and will it be always Buffer? AFAIK it can be string as well

Comment (pro-src) [reply index.js]: > Should we maybe move this to the processResponseBody ? So the code responsible for handling the response is in one place?

The idea there was that we skip should processing of the response body altogether when it's clear that it's not a response type that we should handle. In this case, when body is not a buffer.

> will it be always Buffer? AFAIK it can be string as well

It should always be a buffer unless some other options was passed to change the response type because we're explicity setting the encoding to `null`. I'm pretty sure that `json: true` was the only exception. It might be possible for it to be a string/number but only with the `json: true` option. 

From the docs:
> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.)

Comment (pro-src) [reply index.js]: I can double check the `request` code base if you think it's necessary.

Comment (pro-src) [reply index.js]: @codemanki, I'm double checking this, one sec.

Comment (pro-src) [reply index.js]: Here is the relevant code from `request`. This function is always called because we always set a callback and is responsible for emitting the `complete` event. It is called by `Request.prototype.onRequestResponse` which sets the `response`'s encoding. Essentially `response.setEncoding(request.encoding)`. The response encoding is always `null` because we always explicitly set the `request.encoding` to `null` by passing the encoding option as `null`. This matters in the code linked below because `response` is a `readableStream` which emits the `data` event. The data emitted is ***always*** a buffer when the stream's encoding is `null`. As a matter of fact when `json: true` is based, `JSON.parse` is passed a buffer because of that. So, yes, it is certain that body will always be a buffer and that `json: true` was the only exception. Let me know if you neither any further explanation.

https://github.com/request/request/blob/7195b5064aac02532d4546c9ebcd1ec2508e6223/request.js#L1098-L1156

Comment (pro-src) [reply index.js]: @codemanki, we could even throw an error if body isn't a buffer and `options.json` isn't set because that should never happen.

Comment (codemanki) [reply index.js]: Wow! Thank you for this thorough investigation and explanation.

Comment (pro-src) [reply index.js]: Anytime :smile:

**Comment by codemanki** [comment]
@pro-src LGTM! Shall i release this as 3.1.0?

**Comment by pro-src** [comment]
@codemanki, nah, it's just patches.

**Comment by codemanki** [comment]
Kk. 3.0.1 coming soon

**Comment by codemanki** [comment]
@pro-src oh snap, i can't release from this laptop. Will do it in the evening 🙄
